<?php

/**
 * CrazedCraft Network Economy
 *
 * Copyright (C) 2016 CrazedCraft Network
 *
 * This is private software, you cannot redistribute it and/or modify any way
 * unless otherwise given permission to do so. If you have not been given explicit
 * permission to view or modify this software you should take the appropriate actions
 * to remove this software from your device immediately.
 *
 * @author JackNoordhuis
 *
 * Created on 20/07/2016 at 7:52 PM
 *
 */

namespace kingdomscraft\command\tasks;

use kingdomscraft\economy\provider\mysql\MySQLEconomyProvider;
use kingdomscraft\provider\mysql\MySQLTask;
use pocketmine\Server;

class ViewVaultCommand extends MySQLTask {

	/** @var string */
	protected $who;

	/** @var string */
	protected $to;

	public function __construct(MySQLEconomyProvider $provider, $who, $to) {
		parent::__construct($provider->getCredentials());
		$this->who = strtolower($who);
		$this->to = $to;
	}
	
	public function onRun() {
		$mysqli = $this->getMysqli();
		$result = $mysqli->query("SELECT * FROM economy WHERE username = '{$mysqli->escape_string($this->who)}'");
		if($result instanceof \mysqli_result) {
			$data = $result->fetch_assoc();
			
		}
	}
	
	public function onCompletion(Server $server) {
		parent::onCompletion($server); // TODO: Change the autogenerated stub
	}

}