# Kingdoms Craft Economy plugin - Settings.yml config file
database:
  host: "localhost"
  user: "root"
  password: "root"
  name: "root"
  port: 3306
exp:
  levels:
    # XP required to level up
    2: 10
    3: 20
    4: 30
    5: 40
    6: 50
    7: 60
    8: 70
    9: 80
    10: 90
messages:
  command:
    in-game: "&cPlease run this command in-game!"
