# Kingdoms Craft Economy plugin - Settings.yml config file
basic:
  # Time in seconds between saving all online players economy data
  save-interval: 120
database:
  host: "localhost"
  user: "root"
  password: "root"
  name: "root"
  port: 3306
exp:
  levels:
    # XP required to level up
    2: 10
    3: 20
    4: 30
    5: 40
    6: 50
    7: 60
    8: 70
    9: 80
    10: 90
messages:
  command:
    in-game: "&cPlease run this command in-game!"
    db-connection-error: "&cUh oh, looks like there was an error connecting to the database!"
    set-gold-success: "&aSet {args1}'s gold to {args2}!"
    add-gold-success: "&aGave {args1}'s {args2} gold!"
    take-gold-success: "&aTook {args1} gold from {args2}"
    attempt-set-rubies: "&6Attempting to set {args1}'s rubies..."
    set-rubies-success: "&aSet {args1}'s rubies to {args2}!"
    attempt-set-level: "&6Attempting to set {args1}'s level..."
    set-level-success: "&aSet {args1}'s level to {args2}!"
    attempt-set-xp: "&6Attempting to set {args1}'s xp..."
    set-xp-success: "&aSet {args1}'s xp to {args2}!"
