# Kingdoms Craft Economy plugin - Settings.yml config file
database:
  host: "localhost"
  user: "root"
  password: "root"
  name: "test"
  port: 3306
xp:
  levels:
    2:
      xp: 20
      commands:
        - "stell {args1} You've reached level 2, congrats!"
        - "addgold {args1} 60"
        - "addrubies {args1} 5"
    3:
      xp: 30
      commands:
        - "stell {args1} You've reached level 3, congrats!"
        - "addgold {args1} 70"
        - "addrubies {args1} 10"
    4:
      xp: 40
      commands:
        - "stell {args1} You've reached level 4, congrats!"
        - "addgold {args1} 90"
        - "addrubies {args1} 20"
    5:
      xp: 50
      commands:
        - "stell {args1} You've reached level 5, congrats!"
        - "addgold {args1} 125"
        - "addrubies {args1} 35"
    6:
      xp: 60
      commands:
        - "stell {args1} You've reached level 6, congrats!"
        - "addgold {args1} 150"
        - "addrubies {args1} 50"
    7:
      xp: 70
      commands:
        - "stell {args1} You've reached level 7, congrats!"
        - "addgold {args1} 200"
        - "addrubies {args1} 75"
    8:
      xp: 80
      commands:
        - "stell {args1} You've reached level 8, congrats!"
        - "addgold {args1} 300"
        - "addrubies {args1} 100"
    9:
      xp: 90
      commands:
        - "stell {args1} You've reached level 9, congrats!"
        - "addgold {args1} 400"
        - "addrubies {args1} 150"
    10:
      xp: 100
      commands:
        - "stell {player} You've reached level 10, congrats!"
        - "addgold {args1} 600"
        - "addrubies {args1} 200"
messages:
  command:
    in-game: "&cPlease run this command in-game!"
    player-offline: "&c{args1} is not online!"
    usage: "&cUsage: &6{args1}"
    db-connection-error: "&cUh oh, looks like there was an error connecting to the database!"
    error: "&cOops, looks like there was an error executing the command!"
    cannot-be-negative: "&cValue cannot be negative!"
    no-data: "&cCouldn't find any economy data for {args1}!"
    vault-other: "&e-&6==&e- &a{args1}('s) Vault &e-&6==&e-\n&6Gold: &a{args2}\n&6Rubies: &a{args3}"
    vault-self: "&e-&6==&e- &aYour Vault &e-&6==&e-\n&6Gold: &a{args1}\n&6Rubies: &a{args2}"
    check-level-other: "&e-&6==&e- &a{args1}('s) Level info &e-&6==&e-\n&6XP: &a{args2}\n&6XP till next Level: &a{args3}\n&6Current Level: &a{args4}\n&6Next Level: &a{args5}"
    check-level-self: "&e-&6==&e- &aYour Level info &e-&6==&e-\n&6Gold: &a{args1}\n&6Rubies: &a{args2}"
    pay-success: "Payed {args1} {args2} gold!"
    need-more-gold: "You don't have enough gold to pay {args1}!"
    set-xp-success: "&aSet {args1}('s) XP to {args2}!"
    add-xp-success: "&aGave {args1}('s) {args2} XP!"
    take-xp-success: "&aTook {args1} XP from {args2}"
    top-xp-format: "&a#{args1} &7- &6{args2} &awith &6{args3} &aXP&r"
    top-xp-success: "&e-&6==&e- Top XP &e-&6==&e-\n{args1}"
    set-level-success: "&aSet {args1}('s) level to {args2}!"
    add-level-success: "&aGave {args1}('s) {args2} levels!"
    take-level-success: "&aTook {args1} levels from {args2}"
    set-gold-success: "&aSet {args1}('s) gold to {args2}!"
    add-gold-success: "&aGave {args1}('s) {args2} gold!"
    take-gold-success: "&aTook {args1} gold from {args2}"
    top-gold-format: "&a#{args1} &7- &6{args2} &awith &6{args3} &agold&r"
    top-gold-success: "&e-&6==&e- Top gold &e-&6==&e-\n{args1}"
    set-rubies-success: "&aSet {args1}('s) rubies to {args2}!"
    add-rubies-success: "&aGave {args1}('s) {args2} rubies!"
    take-rubies-success: "&aTook {args1} rubies from {args2}"
    top-rubies-format: "&a#{args1} &7- &6{args2} &awith &6{args3} &arubies&r"
    top-rubies-success: "&e-&6==&e- Top rubies &e-&6==&e-\n{args1}"
