# Kingdoms Craft Economy plugin - Settings.yml config file
database:
  host: "localhost"
  user: "root"
  password: "root"
  name: "test"
  port: 3306
shop:
  identifiers:
    - "shop"
    - "signshop"
    - "signsell"
  format:
    1: "&7[&6Shop&7]&r"
    2: "&6{type} $&a{price}&r"
    3: "&eAmount: &6{amount}&r"
    4: "&e{item}&r"
factions-mode:
  enabled: true
  xp: 5
  take-xp-from-victim: true
  gold: 2
  take-gold-from-victim: true
  message: "&6You gained &a5 XP &6and &a2 gold &6for killing &7{victim}&6!&r"
xp:
  levels:
    2:
      min-xp: 20
      max-xp: 29
      commands:
        - "stell {player} &aYou've reached level &62&a, congrats!"
        - "stell {player} &a+60 &6Gold\n&a+5 &6Rubies"
        - "addgold {player} 60"
        - "addrubies {player} 5"
    3:
      min-xp: 30
      max-xp: 39
      commands:
        - "stell {player} &aYou've reached level &63&a, congrats!"
        - "stell {player} &a+70 &6Gold\n&a+10 &6Rubies"
        - "addgold {player} 70"
        - "addrubies {player} 10"
    4:
      min-xp: 40
      max-xp: 49
      commands:
        - "stell {player} &aYou've reached level &64&a, congrats!"
        - "stell {player} &a+90 &6Gold\n&a+20 &6Rubies"
        - "addgold {player} 90"
        - "addrubies {player} 20"
    5:
      min-xp: 50
      max-xp: 59
      commands:
        - "stell {player} &aYou've reached level &65&a, congrats!"
        - "stell {player} &a+125 &6Gold\n&a+35 &6Rubies"
        - "addgold {player} 125"
        - "addrubies {player} 35"
    6:
      min-xp: 60
      max-xp: 69
      commands:
        - "stell {player} &aYou've reached level &66&a, congrats!"
        - "stell {player} &a+150 &6Gold\n&a+50 &6Rubies"
        - "addgold {player} 150"
        - "addrubies {player} 50"
    7:
      min-xp: 70
      max-xp: 79
      commands:
        - "stell {player} &aYou've reached level &67&a, congrats!"
        - "stell {player} &a+200 &6Gold\n&a+75 &6Rubies"
        - "addgold {player} 200"
        - "addrubies {player} 75"
    8:
      min-xp: 80
      max-xp: 89
      commands:
        - "stell {player} &aYou've reached level &68&a, congrats!"
        - "stell {player} &a+300 &6Gold\n&a+100 &6Rubies"
        - "addgold {player} 300"
        - "addrubies {player} 100"
    9:
      min-xp: 90
      max-xp: 99
      commands:
        - "stell {player} &aYou've reached level &69&a, congrats!"
        - "stell {player} &a+400 &6Gold\n&a+150 &6Rubies"
        - "addgold {player} 400"
        - "addrubies {player} 150"
    10:
      min-xp: 100
      max-xp: 1000000000
      commands:
        - "stell {player} &aYou've reached level &610&a, congrats!"
        - "stell {player} &a+600 &6Gold\n&a+200 &6Rubies"
        - "addgold {player} 600"
        - "addrubies {player} 200"
